# This is an example YAML config file
variables:
  steps: 2
  vars:
##    - name: var1
##      start: 500
##      end: 505
##      step: 1
##      value: &var1 __var1__
    - name: var2
      start: 100
      end: 104
      step: 1
      value: &var2 __var2__

params:
  mass: &mass 1.3089969389957473e-12
  start: 0
  end: .1
  steps: 1000
  initial-conditions: [-1.5e-6, 0, 100.e-6, 0, 0, 0]

output:
  show-main-graph: False
  save-as: test
  graphs:
    - show: False
      name:
      x:
        column: 6
        label: test
        scale: 1
        unit: s
      y:
        column: 0
        label:
        scale: 1.e-6
        unit: $\mu m$
    - show: False
      name:
      x:
        column: 6
        label: test
        scale: 1
        unit: s
      y:
        column: 2
        label:
        scale: 1.e-6
        unit: $\mu m$

forces:
  - type: drag
    params:
      coefficient: 1.7058848108992579e-09
  - type: gravity
    params:
      g: &g [0, 0, -9.8]
      mass: *mass
  - type: buoyancy_sphere
    params:
      g: *g
      density: 1.17845
      radius: &radius 5.e-6
  - type: ray_tracer
    params:
      objects:
        - type: Sphere
          origin:
            type: offset
            value: [0,0,0]
          params:
            radius: *radius
            n_in: 1.52
      ray-factory:
        type: AdaptiveGaussianRF
        origin:
          type: offset
          value: [0, 0, -5.e-6]
        params:
          waist_origin: [0, 0, 0]
          dir: [0,0,1]
          waist_radius: 3.39728e-6
          power: 300.e-3
          n: *var2
          wavelength: 532
          emit_radius: *radius