# This is an example YAML config file
variables:
#  steps: 5
#  vars:
#    - name: var1
#      start: 10
#      end: 100
#      step: 1
#      value: &var1 __var1__

params:
  mass: 1
  start: 0
  end: 5
  steps: 100
  initial-conditions: [1., -1., 0., 0]

forces:
#  - type: restoring
#    params:
#      origin: [0,0]
#      coefficient: 1
  - type: ray_tracer
    params:
      objects:
      - type: Sphere
        params:
          radius: 1.5
          n_in: 1.5
      ray-factory:
        type: BasicRF
        params:
          x: -2
          y: !linspace -1.3, 1.3, 100
          dir: [1,0]
          weight: 10