# This is an example YAML config file
variables:
  steps: 2
  vars:
#    - name: var1
#      start: 5000
#      end: 20000
#      step: 1
#      value: &var1 __var1__
    - name: var2
      start: 100
      end: 1000
      step: 1
      value: &var2 __var2__

params:
  mass: 1.e-11
  start: 0
  end: 50000
  steps: *var2
  initial-conditions: [-30.e-6, 80.e-6, 5.e-8, 0]

forces:
  - type: drag
    params:
      coefficient: 0.001
  - type: constant
    params:
      value: [0, -9.81e-11]
  - type: ray_tracer
    params:
      objects:
#      - type: Sphere
#        origin:
#          type: static
#          value: [-50.e-6,0]
#        params:
#          radius: 50.e-6
#          n_in: 1.3
      - type: Sphere
        origin:
          type: offset
          value: [0,0]
        params:
          radius: 10.e-6
          n_in: 1.5
      ray-factory:
        type: AdaptiveGaussianRF
        origin:
          type: offset
          value: [0, -15.e-6]
        params:
          waist_origin: [0, -15.e-5]
          dir: [0,1]
          waist_radius: 5.e-6
          power: 400.e-3
          n: 100
          wavelength: 600
          emit_radius: 10.e-6
#
#          power: 400.e-3
#          width: 30.e-6
#          dir: [1,0]
#          radius: 50.e-6
#          n: 1000
#          wavelength: 600