# This is an example YAML config file
variables:
#  steps: 5
#  vars:
#    - name: var1
#      start: 10
#      end: 100
#      step: 1
#      value: &var1 __var1__

params:
  mass: 1.e-11
  start: 0
  end: 10000
  steps: 1000
  initial-conditions: [0, -30.e-6, 0., 1.e-8]

forces:
  - type: drag
    params:
      coefficient: 0.001
  - type: ray_tracer
    params:
      objects:
      - type: Sphere
        origin:
          type: static
          value: [0,0]
        params:
          radius: 10.e-6
          n_in: 1.5
      ray-factory:
        type: GaussianRF
        params:
          power: 400.e-3
          width: 30.e-6
          origin: [-1.e-5,0]
          dir: [1,0]
          radius: 20.e-6
          n: 100
          wavelength: 600