# This is an example YAML config file
variables:

params:
  mass: 1.e-11
  start: 0
  end: 25000
  steps: 10
  initial-conditions: [80.e-6, -30.e-6, 0., 0]

forces:
  - type: drag
    params:
      coefficient: 0.001
  - type: constant
    params:
      value: [-9.81e-11, 0]
  - type: ray_tracer
    params:
      objects:
      - type: Sphere
        origin:
          type: static
          value: [-50.e-6,0]
        params:
          radius: 50.e-6
          n_in: 1.3
      - type: Sphere
        origin:
          type: offset
          value: [0,0]
        params:
          radius: 10.e-6
          n_in: 1.5
      ray-factory:
        type: GaussianRF
        params:
          power: 400.e-3
          width: 30.e-6
          origin: [-15.e-5,0]
          dir: [1,0]
          radius: 50.e-6
          n: 1000
          wavelength: 600
