# This is an example YAML config file
variables:
  steps: 1
  vars:
    - name: ray_n
      start: 300
      end: 500
      step: 1
      value: &ray_n __ray_n__

params:
  mass: &mass 1.3089969389957473e-12
  start: 0
  end: .2
  steps: 1500
  initial-conditions: [-1.5e-6, 0, 100.e-6, 0, 0, 0]
  axis: [1, 0, 0]
  rot: 0
  w-init: [0, 0, 0]
  inertia: [1.3089969389957476e-19, 1.3089969389957476e-19, 1.3089969389957476e-19]
  solve_ivp-kwargs:
    atol: [1.e-6, 1.e-6, 1.e-6, 1.e-6, 1.e-6, 1.e-6, 1.e-3, 1.e-3, 1.e-3, 1.e-3, 1.e-3, 1.e-3, 1.e-3]
    rtol: 1.e-2

output:
  show-main-graph: True
  # You can use tags from https://strftime.org/ to include current date elements in this name
  save-as: "%Y-%m-%d-%H-%M-%S-ico-sphere-4-0.2s-limit 2"
#  save-as:
  csv:
    save: True
    sparse: 2
  graphs:
    - show: False
      name: "vx"
      x:
        column: 6
        label:
        scale: 1
        unit: s
      y:
        column: 3
        label:
        scale: 1.e-6
        unit: $\mu m$
    - show: False
      name:
      x:
        column: 6
        label: test
        scale: 1
        unit: s
      y:
        column: 2
        label:
        scale: 1.e-6
        unit: $\mu m$

forces:
  - type: drag
    params:
      coefficient: 1.7058848108992579e-09
  - type: gravity
    params:
      g: &g [0, 0, -9.8]
      mass: *mass
  - type: buoyancy_sphere
    params:
      g: *g
      density: 1.17845
      radius: &radius 5.e-6
  - type: ray_tracer
    params:
      limit: 2
      objects:
#        - type: Sphere
#          origin:
#            type: offset
#            value: [0,0,0]
#          params:
#            radius: *radius
#            n_in: 1.52
        - type: SmoothMeshTO
          origin:
            type: offset
            value: [0,0,0]
          params:
            filename: "objs/ico-4.obj"
            scale: *radius
            n_in: 1.52
      ray-factory:
        type: HexagonalGaussianRF
        origin:
          type: offset
          value: [0, 0, -5.1e-6]
        params:
          waist_origin: [0, 0, 0]
          dir: [0,0,1]
          waist_radius: 3.39728e-6
          power: 300.e-3
          n: *ray_n
          wavelength: 532
          emit_radius: *radius
#          random_switch: True
